### ISSUE TITLE
macOS: Lossless PNG encoding randomly producing extreme small files

### ISSUE THREAD

**Issue by mgenware** [awxkee/jxl-coder-swift#3]
Environment:
```
JxlCoder (1.3.1)
macOS Ventura
```

Repro steps

- Clone and compile this [demo](https://github.com/mgenware/jxlCoderTest) (It does a lossless PNG encoding and saves the result into a tmp file)
- Open a PNG (I took a screenshot on my macOS, a 500KB PNG)
- A Finder window will pop up highlighting the result file
- Do it multiple times with the same source PNG

<img width="739" alt="image" src="https://github.com/awxkee/jxl-coder-swift/assets/11565096/24b930ab-61bd-4dc8-a00f-a7902e57a8a6">

Here's the result on my side. The same 500KB PNG file could end with being 166KB or 32KB randomly.

**Comment by awxkee** [comment]
I've tried your demo but I still getting a constant result. 
May I have some sample image? Do you use x86 Intel mac or M* Apple Silicon?
<img width="995" alt="image" src="https://github.com/awxkee/jxl-coder-swift/assets/17083179/ffe0c421-427e-43f5-b85e-ec994de15976">

**Comment by awxkee** [comment]
Try 1.3.2 version. I think it may solve the issue

**Comment by mgenware** [comment]
Still repros on 1.3.2. I tried multiple files, some never hit this. One particular file seems to have a much higher chance.

I'm on M2 Pro, macOS 13.5.1 (22G90)

<img width="153" alt="image" src="https://github.com/awxkee/jxl-coder-swift/assets/11565096/d9a62762-fb57-4fc9-801c-2894d30850b6">

Attached the zip of that file:

[1.zip](https://github.com/awxkee/jxl-coder-swift/files/13223222/1.zip)

**Comment by awxkee** [comment]
Try out `1.3.3` version. It should works correctly

**Comment by mgenware** [comment]
Upgraded to `1.3.3`, now it's 100% `33KB` instead of `166KB`:

<img width="148" alt="image" src="https://github.com/awxkee/jxl-coder-swift/assets/11565096/cab4e3cf-5954-4f20-9b24-49a82da82875">

**Comment by awxkee** [comment]
Yes, it is expected. Bug was producing invalid background colors that was increasing a file size

**Comment by mgenware** [comment]
Both `cjxl -q 100` and [squoosh.app](https://squoosh.app/) (lossless) produce a 177KB jxl

**Comment by awxkee** [comment]
Yes, because it may detect that original file uses `RGBA` ( 4 channel with alpha ) and compress it in RGBA. If you'll set `colorSpace: .rgba` in encoder parameters you will get close result to it. Default value is rgb that replaces alpha channel to black that you may have already noticed in result files. I add that implicit option to choose compressing in RGB or RGBA since in Apple platform almost no `clear` ways to understand original pixel format because it must be always be redrawn in premultiplied RGBA pixel format. And RGB was chosen as default because primary target of JPEG XL is photos that do not contains alpha channel.

**Comment by awxkee** [comment]
So the main responsibility to choose between RGB or RGBA pixel format is delegated to the caller

**Comment by mgenware** [comment]
I see. Thanks for the explanation. Can confirm it's working after switching to `.rgba`.
